### ISSUE TITLE
Build Problem

### ISSUE THREAD

**Issue by kimhys** [tobyli/Sugilite_development#114]
Hello

I am hs.kim in south korea.
I just tried to build latest code of master branch with Android Studio. And got below problem.
Could you please let me know how to fix?

/home/xxxxxxx/Sugilite_development/app/src/main/java/edu/cmu/hcii/sugilite/source_parsing/SugiliteScriptExpression.java:3: error: cannot find symbol
import edu.cmu.hcii.sugilite.model.operation.unary.SugiliteLaunchAppOperation;
                                                  ^
  symbol:   class SugiliteLaunchAppOperation
  location: package edu.cmu.hcii.sugilite.model.operation.unary

**Comment by tobyli** [comment]
Fixed in the latest commit.

Note that you'll also need to place your Google Cloud credential json (see https://cloud.google.com/docs/authentication/getting-started) for speech recognition in res/raw/credential.json for it to build.

Let me know if you have any other questions! Thanks.
